/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.learnprogramming.java8;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void dummyTest() {
        assertTrue(true);
    }
}
